classDiagram
DataSharingPlatform *-- DataOwnerInterface: provides
DataSharingPlatform *-- DataSharingWorkflow: provides
DataSharingPlatform *-- DataSharingCommunication: provides 
DataOwnerInterface *-- GetAccessWorkflow: provides
DataOwnerInterface *-- Connect: provides
DataOwnerInterface *-- Upload: provides
DataOwnerInterface *-- AdminDataSharing: provides
GetAccessWorkflow *-- FirstAccessWorkflow: has
GetAccessWorkflow *-- SecurityUpdateWorkflow: has
AdminDataSharing *-- SharedData: administrate
AdminDataSharing *-- DataSharingConsumptionReport: provide   
class SharedData
claas GetAccessWorkflow
class SecurityUpdateWorkflow
class FirstAccessWorkflow
class AdminDataSharing
class DataSharingConsumptionReport
class Upload
class Connect
class DataOwnerInterface
class DataSharingPlatform