graph TD
A0(Data Requester / FAIRplus researcher):::box1 -->|requests data access from|B(Study Sponsor / IMI Project):::box1
A0 -->|produces|A1(research proposal):::box2
A11:::box1 -->|made available to|B(Study Sponsor / IMI Project):::box1
A00(FAIRplus consortium):::box1 -->|produces|A11(Confidentiality Disclosure <br> & <br> Collaboration Agreement):::box2
B-->|delegates decision to|B0
B0(Data Custodian):::box1 -->|performs|D

A1 -->|made available to|B
  B -->|checks|C1
  B0 -->|checks|C1
  C1[eligibility criteria]:::box2 -->|used by|D
  B -->|performs|D{data access request <br> evaluation  process}:::box4
  D -->|request rejected| A2(Negotiation Protocol ends):::box
  D -->|request approved|D1(Negotiation Protocol proceeds):::box3
  D1 -->F
  B -->|prepares legal document|F(Data Use Agreement):::box2

  F -->|defines|G(data use limitations):::box5
  G -->|allows|G1(disease specific research):::box5
  F -->|imposes|F3(data use requirements, <br> e.g. `geographical restriction`):::box5
  G -->|prohibits|F2(data redistribution):::box5
  F -->|signature requested from|A0

  UL(Data Processor / UL):::box1 -->|hosts data|I(test):::box1
  B-->|transfers data to|UL

  classDef box1 font-family:avenir,font-size:14px,fill:#2a9fc9,stroke:#222,color:#fff,stroke-width:1px
  classDef box2 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#red,stroke-width:1px
  classDef box font-family:avenir,font-size:14px,fill:darkred,stroke:#222,color:#fff,stroke-width:1px
  classDef box3 font-family:avenir,font-size:14px,fill:green,stroke:#222,color:#fff,stroke-width:1px
  classDef box4 font-family:avenir,font-size:14px,fill:lightblue,stroke:#222,color:#fff,stroke-width:1px
  classDef box5 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px
  