graph TD
    step1[Review of existing clinical trials registery]:::box --> step2[List of metadata elements]:::box
    step2 --> step3[Expert feedback]:::box
    step3 --> step4[Refined list of metadata elements]:::box
    step4 --> step5[Sample implementation using a representative clinical trial]:::box
    step4 --> step6[Creation of a metadata template]:::box
    step6 --> step7[Excel spreadsheet]:::box
    step6 --> step8[REDCap survey]:::box
    step5 --> step9[User feedback]:::box
    step7 --> step9
    step8 --> step9
    step9 --> step10[Actionable metadata profile]:::box


classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
linkStyle 0,1,2,3,4 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;
