graph TD;
    A[Data FAIRification] -->B(Write-up FAIRification experience)
    B --> C{know markdown?}
    C -->|Yes| D(use the markdown recipe template)
    C -->|No| E(use Google doc recipe template instead)