classDiagram
SharedData "1" *-- "1..*" Dataset: has
Dataset "1" *-- "1" Data: has
Dataset "1" *-- "0..1" DatasetProfile: has
Dataset "1" *-- "1" DatasetMetadata: has
SharedData "1..*" *-- "1" ConsumerLicenceDefinition: has
SharedData "1..*" *-- "0..1" ProviderLicenceDefinition: has
DatasetMetadata "1" *-- "1" DatasetLevelMetadata: has
DatasetMetadata "1" *-- "0..*" ColumnMetadata: has
DatasetMetadata "1" *-- "0..1" ProvenanceMetadata: has
DatasetMetadata "1" *-- "0..1" QualityMetadata: has
class SharedData
class Dataset
class Data
class DatasetMetadata
class ProviderLicenceDefinition
class ConsumerLicenceDefinition
class DatasetLevelMetadata
class ColumnMetadata
class ProvenanceMetadata