graph TD;
	A(fa:fa-users Identification of project selection <br> and prioritization team) --> |Collect dataset relevant information|B[(Project corpus creation)]
    B--> |Creating factor checklist| C(fa:fa-th-list Prioritization of projects based <br> on factor list)
    C--> |Adding points for factors into a scoreboard| D(fa:fa-sort Scorecard formulation and project <br> ranking)