graph TD
  A([file creation]):::box -->  B(New File):::box  
  B -->  C{need for a <br>stable <br>identifier?}:::box 
  C --> |Yes| D([invoke MINID minting service]):::box 
  C -->  |No| E(no findable data):::box1 -->
  D -->  F([hdl:20.500.12633/1HK1DTv1wPt3a]):::box 

classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
classDef box1 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px
linkStyle 0,1,2,3,4,5 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir
