graph TD
Process2[Identifier Minting]:::bix --> A1(authority decide identity):::box
Process2 --> Process3
Process3[URI construction]:::bix --> A2(scoping the authority):::box
Process3 --> Process4
Process4[URI resolution]:::bix --> A3(directing requests to the relevant identified entity):::box
classDef bix font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px
classDef box font-family:avenir,font-size:14px,fill:#2a9fc9,stroke:#222,color:#fff,stroke-width:1px

classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
classDef box1 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px
linkStyle 0,1 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;