graph TB;

subgraph Performance Questions
Perf1[Does the system provide a scalable architecture?]
Perf2[Is the volume of existing installations equal or beyond my volume?]
Perf3[Is the number of users of existing installations similar or beyond my number of users?]
Perf4[Does the system collect performance indicators?]
PerfL[Does the system offer automatic performance measurements?]
end
Perf1 --> Perf2 --> Perf3 --> Perf4 --> PerfL