graph TB;

subgraph "Costs Questions (Initial and Ongoing)"
Cost1[Are the software licence costs acceptable?]
Cost2[Are the database licence costs acceptable?]
Cost3[Are the hardware costs acceptable?]
Cost4[Are the training costs acceptable?]
Cost5[Are the support costs acceptable?]
CostL[Are the customization costs acceptable?]
end
Cost1 --> Cost2 --> Cost3 --> Cost4 --> Cost5 --> CostL