graph TD
    A[Data collection] -->B(Enriched metadata)
    B1{Minimum information checklist} -->B
    B --> C(Annotaed metadata)
    C1{Recommended data models} -->C
    C --> D[Processed assay data]
    D--> E[Formatted datasets]
    E1{Format requirements} -->E
    E--> F[Submission-ready datasets]
    classDef standards stroke:#f66,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
    class B1,C1,E1 standards
end