graph TD
    A[Data collection] -->B(Enriched metadata)
    B1{Minimum information checklist} -->B
    B --> C(Annotated metadata)
    C1{Recommended data models} -->C
    C --> D[Processed assay data]
    D--> E[Formatted datasets]
    E1{Format requirements} -->E
    E--> F[Submission-ready datasets]
    
