graph LR 
      classDef sources stroke-width:4px;

      class En sources;
      class X sources;
      class Local sources;

      classDef BDb fill: #d5fca6, fontSize: 40px, stroke-width:6px, stroke: #000
      class BridgeDb BDb;

      1234 <==>  AF1
      5555 <==> AF3
      6789 <==> AF2

      subgraph Local
        1234
        5555
        6789
      end


      subgraph BridgeDb
        AF1 --> ZM1
        AF1 --> ZM2
        AF1 --> ZM3
        AF2 --> ZM4
        AF3 --> ZM4
        subgraph Affy
          AF1[AFFX-Zm-ef1a-5_a_at]
          AF2[AFFX-Zm_Ubiquitin_M_f_at]
          AF3[AFFX-Zm_Ubiquitin_5_f_at]
        end
        subgraph Ensembl
          ZM1[Zm00001d037873]
          ZM2[Zm00001d037877]
          ZM3[Zm00001d037875]
          ZM4[Zm00001d053838]
        end
      end