  graph TB 
      subgraph Script

          subgraph BridgeDb
              B[Affy]-->E[Gene Ontology]
              B[Affy]-->F[Ensembl]
              B[Affy] --> H[UniProt]
          subgraph Pre-made mapping
            A[Local identifier source]-->B[HGNC]
          end
          end
        end