graph TD
A[Defining a Metadata Requirement Profile: Transcriptomics Data]:::box --> Z:::box
Z(fa:fa-pie-chart Requirement Analysis) --> W[fa:fa-file-text fa:fa-bars List of Requirements: Minimal vs Recommended] 
W:::box --> |Survey State of the Art| C{fa:fa-binoculars <br/> Is there prior work?}:::box 
C --> |No| E[fa:fa-magic Create Checklist fa:fa-check-square fa:fa-check-square fa:fa-square-o fa:fa-check-square]:::box 
C --> |Yes| D[ Query of FAIRSharing.org <br>Retrieval of:<br>Genome Standards Consortium  <br>MIUVIG - Minimum Information About an Uncultivated Virus Genome]:::box1
D --> G{Evaluation: is it enough?}:::box2 
G --> |Yes| H[fa:fa-recycle Reuse Checklist fa:fa-check-square fa:fa-check-square fa:fa-square-o fa:fa-check-square]:::box1 
G --> |No| I[fa:fa-code-fork Extend Checklist fa:fa-check-square  fa:fa-check-square fa:fa-square-o fa:fa-check-square fa:fa-check-square]:::box
H --> K{Machine actionable checklist? <br/> fa:fa-code fa:fa-cogs}:::box2
E --> K{Machine actionable checklist? <br/> fa:fa-code fa:fa-cogs}:::box2
I --> K{Machine actionable checklist? <br/> fa:fa-code fa:fa-cogs}:::box2
K --> |Entity Mapping to Ontology| L[ontology tagged requirements]:::box1 
K --> |Entity Data Typing| M[Data typed requirements]:::box1
M --> |Definition of value sets| N[Ontology constrained fa:fa-link requirements]:::box5 
K --> |Formalization| J[Machine Readable Metadata Profile fa:fa-code fa:fa-cogs fa:fa-code]:::box1 
J --> |Implementation| O[User Friendly Metadata Collection e.g. Form, Tabular template fa:fa-file-excel-o fa:fa-file-excel-o fa:fa-file-excel-o fa:fa-group fa:fa-group fa:fa-group]:::box5 

linkStyle 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;

classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
classDef box2 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px
classDef box1 font-family:avenir,font-size:14px,fill:purple,stroke:#222,color:#fff,stroke-width:1px
classDef box5 font-family:avenir,font-size:14px,fill:#FF3371,stroke:#222,color:#fff,stroke-width:1px