graph TD
  A[Defining a Metadata Requirement Profile: Transcriptomics Data]:::box --> Z:::box
  Z(fa:fa-pie-chart Requirement  Analysis) --> W[fa:fa-file-text fa:fa-bars List of  Requirements: Minimal vs Recommended]

  W:::box --> |Survey State of the Art| C{fa:fa-binoculars <br> Is there<br> prior work?}:::box1


  C --> |No| E[fa:fa-magic Create Checklist <br>fa:fa-check-square<br>fa:fa-check-square<br>fa:fa-square-o<br>fa:fa-check-square]:::box
  C --> |Yes| D[Minimum Information Checklist]:::box
  D --> G{Evaluation:<br> is it enough?}:::box1
  G --> |Yes| H[fa:fa-recycle Reuse Checklist <br>fa:fa-check-square<br>fa:fa-check-square<br>fa:fa-square-o<br>fa:fa-check-square]:::box
  G --> |No| I[fa:fa-code-fork Extend Checklist <br>fa:fa-check-square<br>fa:fa-check-square<br>fa:fa-square-o<br>fa:fa-check-square<br>fa:fa-check-square]:::box
  H --> K{Machine<br> actionable<br> checklist?<br>fa:fa-code<br> fa:fa-cogs}:::box1
  E --> K{Machine<br> actionable<br> checklist?<br>fa:fa-code<br> fa:fa-cogs}:::box1
  I --> K{Machine<br> actionable<br> checklist?<br>fa:fa-code<br> fa:fa-cogs}:::box1
  K --> |Entity Mapping to Ontology| L[ontology<br> tagged <br>requirements]:::box

  K --> |Entity Data Typing| M[Data<br> typed<br> requirements]:::box
  M --> |Definition of value sets| N[Ontology<br> constrained<br> fa:fa-link requirements]:::box
  K --> |Formalization| J[Machine Readable Metadata Profile <br>fa:fa-code<br> fa:fa-cogs<br>fa:fa-code]:::box
  J --> |Implementation| O[User Friendly Metadata Collection <br> e.g. Form, Tabular template <br> fa:fa-file-excel-o fa:fa-file-excel-o fa:fa-file-excel-o<br> fa:fa-group fa:fa-group fa:fa-group]:::box
  
  linkStyle 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;
  classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
  classDef box1 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px