    graph TB
      I[Identifier]
      I --> IM[Identifier Mapping]
      M[Mapping Process] --> OM[Ontology Mapping]
      OM --> OxO[OxO Service]

      M --> IM

      IM -- performs --> IMS

      IM -- performs--> IE([Identifier Equivalence Assessment])
      IE -- uses service--> SL{{Scientific Lenses}}

      IMS([Identifier Mapping Services])
      IMS -- uses service --> BDb[BridgeDb]
      IMS -- uses service --> UniChem{{UniChem}}
      IMS -- uses service --> Sameas{{Sameas}}
      IMS -- uses service --> Identifiers{{Identifiers.org}}

      BDb -- performs --> MGG[Mapping global identifiers to other global identifiers]
      BDb -- performs --> MLG[Mapping local identifiers to other global identifiers]

      MGG -- implemented in --> P1([Python])
      MGG -- implemented in --> R1([R])
      MLG -- implemented in --> P2([Python])
      MLG -- implemented in --> R2([R])
      
        style OM stroke-dasharray: 5 5
        %% style M stroke-dasharray: 5 5

       classDef select font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px;
       classDef box1 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px;
       class IM select;
       class IMS select;
       class MGG select;
       class MLG select;
       class OM select;
      
       class BDb select;
       class UniChem select;
       class Sameas select;
       class Identifiers select;
       class M select;
       class IE select;
       class SL box1;
       class UniChem box1;
       class BDb box1;
       class Sameas box1;
       class Identifiers box1;
       class P1 box1;
       class P2 box1;
       class R1 box1;
       class R2 box1;
      %% style IM fill:orange
      %% style I fill:#B30000


classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px

linkStyle 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;