graph TB
    subgraph Ontology strategies
    
        subgraph Metadata enrichment
            A[Ontology recommendation]
            B[Ontology annotation]
            C[Ontology mapping]
        end
        
        subgraph Ontology life cycle
            D[Ontology engineering]
            E[Ontology management]
        end
        
        A-->B
        B-->C
        
        E-.-A
        E-.-C
        
        
    end
    
    classDef className fill:#f9f,stroke:#333,stroke-width:2px
