graph TB
    A(Identify source ontology term ID)
    B(Select target ontology)
    C(Perform mapping)
    D(Review mapping results)

    B-->A
    A-->C
    C-->D

    E((OLS))
    F((ZOOMA))
    G((OxO))

    A-.-E
    A-.-F
    B-.-E
    D-.-E
    C-.-G

    style A font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
    style B font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
    style C font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
    style D font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px


    style E fill:#708c98 ,stroke-width:0px
    style F fill:#708c98 ,stroke-width:0px
    style G fill:#708c98 ,stroke-width:0px
