graph LR
  A(fa:fa-file-text-o Select seed terms):::box -->B1(fa:fa-user-o Manual selection):::box
  A -->B2(fa:fa-database Selection with ZOOMA):::box
  A -->B3(fa:fa-database Selection with NCBO Annotator):::box
  A -->B4(fa:fa-cogs Selection with SPARQL):::box

  classDef box font-family:avenir,font-size:14px,fill:#2a9fc9,stroke:#222,color:#fff,stroke-width:1px