graph TD;
  I1(fa:fa-university ontology source 1):::box -->|extract| M1(fa:fa-cube ontology module 1):::box
  I2(fa:fa-university ontology source 2):::box -->|extract| M2(fa:fa-cube ontology module 2):::box
  I3(fa:fa-university ontology source 3):::box -->|extract| M3(fa:fa-cube ontology module 3):::box
  M1 --> |merge| R1(fa:fa-cubes core):::box
  M2 --> |merge| R1(fa:fa-cubes core):::box
  M3 --> |merge| R1(fa:fa-cubes core):::box
  R1(fa:fa-cubes core):::box --> |materialize| R2(fa:fa-cubes reasoned & reduced core):::box

  R2(fa:fa-cubes reasoned & reduced core) -->|report| R3(fa:fa-tasks report):::box
  R2(fa:fa-cubes reasoned & reduced core) --> |edit| R4(fa:fa-cubes reasoned & reduced core):::box
  R3 -->|edit| R4
  R4 -->|annotate| R5(fa:fa-cubes fa:fa-tags fa:fa-cc annotated,reasoned,reduced core):::box
  R5 -->|convert| R6(fa:fa-star-o obo version):::box
  R5 -->|convert| R7(fa:fa-star owl version):::box

classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
linkStyle 0,1,2,3,4,5,6,7,8,9,10,11,12 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;
