graph TD
    
    subgraph ETL-RDF
        subgraph Data extraction

            A1[Data query and retrieval]
        end

        subgraph Data transform
            B1[Data annotation]
            B2[Data validation]
            B3[Data aggregation]
        end

        C[Data deposition]

        A1-->B1
        B1-->B2
        B2-->B3
        B3-->C
        B3-.->D[RDF visualization]
    end