graph TD;
  I1(fa:fa-university what is the context?):::box -->|framework| M1(fa:fa-cube clinical trial context):::box
  I1(fa:fa-university what is the context?) -->|framework| M2(fa:fa-cube observational patient outcome):::box
  I1(fa:fa-university what is the context?) -->|framework| M3(fa:fa-cube basic research):::box

  M1 --> |consider| R1(fa:fa-cubes CDISC Vocabulary):::box
  M2 --> |consider| R2(fa:fa-cubes OHDSI Athena terminologies):::box
  M3 --> |consider| R3(fa:fa-cubes OBO Foundry resources):::box
  
  I2{fa:fa-university is public<br> archive<br> deposition <br>required? }:::box2 -->|No |R3:::box
  I2{fa:fa-university is public<br> archive<br> deposition <br>required? } -->|Yes|M4(consult FAIRsharing):::box

  M4 --> |EBI resources|M5(EFO):::box

  linkStyle 0,1,2,3,4,5,6,7,8 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;
  classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
  classDef box2 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px