graph TD
 A:::box
 A[Data on source repository] --> B(Decide in needed location):::box
    B --> C{Do you have an account <br/>on source repository?}:::box1
    C -->|Yes| D[Decide how you are you going access the data]:::box
    C -->|No| E[Obtain access credentials on source repository]:::box
    D -->H(Install download/upload software):::box
    H -->I(Work out the appropriate command line options):::box
    I -->Z{Does your system have <br/>the applicable firewall holes?}:::box1
    Z -->|Yes| J(Start download):::box
    Z -->|No| G[Get firewall holes]:::box
    G --> J
    J -->K(Monitor download and check download speed):::box
    K -->L(Check download and create a mini data catalogue):::box

classDef box font-family:avenir,font-size:14px,fill:#B30000,stroke:#222,color:#fff,stroke-width:1px
classDef box1 font-family:avenir,font-size:14px,fill:orange,stroke:#222,color:#fff,stroke-width:1px
linkStyle 0,1 stroke:#B30000,stroke-width:1px,color:#B30000,font-family:avenir;